language: cpp
os: linux

matrix:
  include:
    - os: osx
      osx_image: osx10.11
      env: OSX=10.11
      compiler: clang
    - os: osx
      osx_image: xcode7
      env: OSX=10.10
      compiler: clang
    - os: osx
      osx_image: beta-xcode6.2
      env: OSX=10.9
      compiler: clang
    - os: linux

before_install:
    - git clone https://gist.github.com/tkralphs/13d4529b4d4e8889f3a6 scripts
    - bash scripts/get.dependencies.sh fetch

install: bash scripts/get.dependencies.sh build

script: make test
