platform:
  - x64
environment:
  global:
    MSYS2_BASEVER: 20150512
  matrix:
    - MSYS2_ARCH: x86_64
install:
  - C:\"Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat"
  - appveyor DownloadFile "http://kent.dl.sourceforge.net/project/msys2/Base/%MSYS2_ARCH%/msys2-base-%MSYS2_ARCH%-%MSYS2_BASEVER%.tar.xz" -FileName "msys2.tar.xz"
  - 7z x msys2.tar.xz
  - 7z x msys2.tar > NUL
  - msys64\usr\bin\bash -lc ""
  - msys64\usr\bin\bash -lc "for i in {1..3}; do pacman --noconfirm -Suy make wget tar patch dos2unix diffutils && break || sleep 15; done"

build_script:
  - msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; git clone https://gist.github.com/tkralphs/13d4529b4d4e8889f3a6 scripts; ./scripts/get.dependencies.sh fetch build --no-third-party --monolithic --build=x86_64-w64-mingw32 --enable-msvc --test"

test: off